# Generated by Django 3.2 on 2021-04-20 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('qldh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tintuc',
            name='tao_boi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qldh.adminuser'),
        ),
    ]
