# Generated by Django 3.2 on 2021-04-20 05:21

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[(1, 'Admin'), (2, 'Giáo Viên'), (3, 'Học Sinh')], default=1, max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DiemSo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoc_ky', models.CharField(max_length=50)),
                ('diem', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='GiangDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MonHoc',
            fields=[
                ('ma_mon', models.CharField(default='', max_length=5, primary_key=True, serialize=False)),
                ('ten_mon', models.CharField(default='', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NamHoc',
            fields=[
                ('nam_hoc', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('mo_ta', models.CharField(default='', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhongHoc',
            fields=[
                ('map_hong', models.CharField(default='', max_length=5, primary_key=True, serialize=False)),
                ('ten_phong', models.CharField(default='', max_length=50, unique=True)),
                ('so_luong_cho_ngoi', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TrinhDoHocVan',
            fields=[
                ('trinh_do', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('mo_ta_trinh_do', models.CharField(default='', max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('ma_admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='qldh.customuser', to_field='username')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiemSo_ChiTiet',
            fields=[
                ('mads', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='qldh.diemso')),
                ('diem_mieng', models.FloatField(default=0.0)),
                ('diem_15_phut', models.FloatField(default=0.0)),
                ('diem_45_phut', models.FloatField(default=0.0)),
                ('diem_thi', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='GiaoVien',
            fields=[
                ('magv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='qldh.customuser', to_field='username')),
                ('so_dien_thoai', models.CharField(default='', max_length=10, null=True)),
                ('que_quan', models.TextField()),
                ('ngay_sinh', models.DateField(default=datetime.datetime(1900, 1, 1, 0, 0))),
                ('gioi_tinh', models.CharField(max_length=50)),
                ('day_mon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qldh.monhoc')),
                ('trinh_do', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qldh.trinhdohocvan')),
            ],
        ),
        migrations.CreateModel(
            name='HocSinh',
            fields=[
                ('mahs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='qldh.customuser', to_field='username')),
                ('que_quan', models.TextField()),
                ('ngay_sinh', models.DateField(default=datetime.datetime(1900, 1, 1, 0, 0))),
                ('gioi_tinh', models.CharField(max_length=50)),
                ('dan_toc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LopHoc',
            fields=[
                ('ma_lop', models.CharField(default='', max_length=6, primary_key=True, serialize=False)),
                ('ten_lop', models.CharField(default='', max_length=50, unique=True)),
                ('si_so', models.IntegerField(default=0)),
                ('khoi', models.CharField(max_length=50)),
                ('phong', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='qldh.phonghoc', to_field='ten_phong')),
                ('giao_vien_chu_nhiem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='qldh.giaovien')),
            ],
        ),
        migrations.CreateModel(
            name='GiangDay_ChiTiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thu', models.CharField(max_length=50)),
                ('buoi', models.CharField(max_length=50)),
                ('tiet_bd', models.CharField(default='', max_length=2)),
                ('tiet_kt', models.CharField(default='', max_length=2)),
                ('so_tiet', models.IntegerField(default=0)),
                ('magd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qldh.giangday')),
            ],
        ),
        migrations.AddField(
            model_name='giangday',
            name='ma_lop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qldh.lophoc', to_field='ten_lop'),
        ),
        migrations.AddField(
            model_name='giangday',
            name='nam_hoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qldh.namhoc', to_field='mo_ta'),
        ),
        migrations.AddField(
            model_name='diemso',
            name='mon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qldh.monhoc', to_field='ten_mon'),
        ),
        migrations.AddField(
            model_name='diemso',
            name='nam_hoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qldh.namhoc', to_field='mo_ta'),
        ),
        migrations.CreateModel(
            name='KetQuaHocTap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xep_loai', models.CharField(max_length=50)),
                ('hanh_kiem', models.CharField(max_length=50)),
                ('nam_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qldh.namhoc', to_field='mo_ta')),
                ('mahs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qldh.hocsinh')),
            ],
        ),
        migrations.AddField(
            model_name='hocsinh',
            name='lop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qldh.lophoc', to_field='ten_lop'),
        ),
        migrations.AddField(
            model_name='giangday',
            name='magv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qldh.giaovien'),
        ),
        migrations.AddField(
            model_name='diemso',
            name='mahs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qldh.hocsinh'),
        ),
    ]
