# Generated by Django 3.2 on 2021-04-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qldh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giaovien',
            name='profile_pic',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='hocsinh',
            name='profile_pic',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
