# Generated by Django 3.2 on 2021-04-20 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qldh', '0002_auto_20210420_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giaovien',
            name='magv',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
