# Generated by Django 3.2 on 2021-04-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qldh', '0004_alter_giaovien_magv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giaovien',
            name='gioi_tinh',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='giaovien',
            name='que_quan',
            field=models.TextField(default=''),
        ),
    ]
