# Generated by Django 3.2 on 2021-04-22 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qldh', '0007_rename_map_hong_phonghoc_ma_phong'),
    ]

    operations = [
        migrations.AddField(
            model_name='lophoc',
            name='nam_hoc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qldh.namhoc'),
        ),
    ]
