# Generated by Django 3.2 on 2021-04-22 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qldh', '0010_auto_20210422_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lophoc',
            name='nam_hoc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qldh.namhoc', to_field='mo_ta'),
        ),
        migrations.AlterField(
            model_name='lophoc',
            name='phong',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='qldh.phonghoc', to_field='ten_phong'),
        ),
    ]
