# Generated by Django 3.2 on 2021-05-06 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qldh', '0016_diemso_trang_thai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diemso',
            name='hoc_ky',
        ),
    ]
