# Generated by Django 3.2 on 2021-05-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qldh', '0017_remove_diemso_hoc_ky'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ketquahoctap',
            name='hanh_kiem',
            field=models.CharField(default='Chưa đánh giá', max_length=50),
        ),
        migrations.AlterField(
            model_name='ketquahoctap',
            name='xep_loai',
            field=models.CharField(default='Chưa đánh giá', max_length=50),
        ),
    ]
