# Generated by Django 3.2 on 2021-05-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qldh', '0018_auto_20210507_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='diemso',
            name='hoc_ky',
            field=models.CharField(default='Chưa nhập', max_length=50),
        ),
        migrations.AddField(
            model_name='giangday',
            name='hoc_ky',
            field=models.CharField(default='Chưa nhập', max_length=50),
        ),
        migrations.AddField(
            model_name='ketquahoctap',
            name='hoc_ky',
            field=models.CharField(default='Chưa nhập', max_length=50),
        ),
    ]
