# Generated by Django 3.2 on 2021-05-14 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qldh', '0019_auto_20210514_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ketquahoctap',
            name='hoc_ky',
        ),
    ]
