# Generated by Django 4.0.1 on 2022-02-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qldh', '0020_remove_ketquahoctap_hoc_ky'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monhoc',
            name='ma_mon',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
