# Generated by Django 4.0.1 on 2022-02-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qldh', '0021_alter_monhoc_ma_mon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lophoc',
            name='ma_lop',
            field=models.CharField(default='', max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='phonghoc',
            name='ma_phong',
            field=models.CharField(default='', max_length=8, primary_key=True, serialize=False),
        ),
    ]
