# Generated by Django 4.0.1 on 2022-03-20 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qldh', '0023_auto_20220320_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='HocKy',
            fields=[
                ('hoc_ky', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('hien_tai', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='giangday',
            name='thu',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='giangday',
            name='tiet_1',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='giangday',
            name='tiet_2',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='giangday',
            name='tiet_3',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='giangday',
            name='tiet_4',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='giangday',
            name='tiet_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='giangday',
            name='tiet_6',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='giangday',
            name='tiet_7',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='giangday',
            name='tiet_8',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='giangday',
            name='tiet_9',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='namhoc',
            name='hien_tai',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='giangday',
            name='ma_lop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='qldh.lophoc'),
        ),
        migrations.AlterField(
            model_name='giangday',
            name='magv',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='qldh.giaovien'),
        ),
        migrations.AlterUniqueTogether(
            name='giangday',
            unique_together={('magv', 'ma_lop', 'thu')},
        ),
        migrations.DeleteModel(
            name='GiangDay_ChiTiet',
        ),
    ]
