# Generated by Django 4.0.1 on 2022-03-22 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qldh', '0024_hocky_giangday_thu_giangday_tiet_1_giangday_tiet_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giangday',
            name='ma_lop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qldh.lophoc'),
        ),
        migrations.AlterField(
            model_name='giangday',
            name='magv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qldh.giaovien'),
        ),
    ]
