# Generated by Django 4.0.1 on 2022-03-22 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qldh', '0025_alter_giangday_ma_lop_alter_giangday_magv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giangday',
            name='thu',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(2)]),
        ),
    ]
