# Generated by Django 4.0.1 on 2022-03-22 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qldh', '0026_alter_giangday_thu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giangday',
            name='thu',
            field=models.IntegerField(default=8, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(2)]),
        ),
    ]
