# Generated by Django 4.0.1 on 2022-03-23 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qldh', '0027_alter_giangday_thu'),
    ]

    operations = [
        migrations.AddField(
            model_name='ketquahoctap',
            name='hoc_ky',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='qldh.hocky'),
        ),
        migrations.AlterField(
            model_name='diemso',
            name='hoc_ky',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='qldh.hocky'),
        ),
        migrations.AlterField(
            model_name='giangday',
            name='hoc_ky',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='qldh.hocky'),
        ),
    ]
