# Generated by Django 4.0.1 on 2022-03-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qldh', '0028_ketquahoctap_hoc_ky_alter_diemso_hoc_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monhoc',
            name='tiet_tuan',
            field=models.IntegerField(default=0),
        ),
    ]
