# Generated by Django 4.0.1 on 2022-03-29 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qldh', '0030_alter_giangday_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='giangday',
            unique_together={('ma_lop', 'nam_hoc', 'hoc_ky', 'thu', 'tiet_1'), ('ma_lop', 'nam_hoc', 'hoc_ky', 'thu', 'tiet_4'), ('ma_lop', 'nam_hoc', 'hoc_ky', 'thu', 'tiet_3'), ('ma_lop', 'nam_hoc', 'hoc_ky', 'thu', 'tiet_8'), ('ma_lop', 'nam_hoc', 'hoc_ky', 'thu', 'tiet_7'), ('ma_lop', 'nam_hoc', 'hoc_ky', 'thu', 'tiet_9'), ('ma_lop', 'nam_hoc', 'hoc_ky', 'thu', 'tiet_6'), ('ma_lop', 'nam_hoc', 'hoc_ky', 'thu', 'tiet_2'), ('ma_lop', 'nam_hoc', 'hoc_ky', 'thu', 'tiet_5')},
        ),
    ]
