# Generated by Django 4.0.1 on 2022-03-29 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qldh', '0031_alter_giangday_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='giangday',
            unique_together={('ma_lop', 'nam_hoc', 'hoc_ky', 'thu', 'tiet_1', 'tiet_2', 'tiet_3', 'tiet_4', 'tiet_5', 'tiet_6', 'tiet_7', 'tiet_8', 'tiet_9')},
        ),
    ]
