# Generated by Django 4.0.1 on 2022-04-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qldh', '0033_giangday_cal_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diemso',
            old_name='diem',
            new_name='tb',
        ),
        migrations.RemoveField(
            model_name='diemso',
            name='trang_thai',
        ),
        migrations.AddField(
            model_name='diemso',
            name='hk',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='diemso',
            name='m1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='diemso',
            name='m2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='diemso',
            name='m3',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='diemso',
            name='p1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='diemso',
            name='p2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='diemso',
            name='p3',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='diemso',
            name='p4',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='diemso',
            name='t1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='diemso',
            name='t2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='diemso',
            name='t3',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='diemso',
            name='t4',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='diemso',
            name='t5',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='diemso',
            name='t6',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='diemso',
            name='t7',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='diemso',
            name='t8',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='DiemSo_ChiTiet',
        ),
    ]
