# Generated by Django 4.0.1 on 2022-04-14 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qldh', '0034_rename_diem_diemso_tb_remove_diemso_trang_thai_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HanhKiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hanh_kiem', models.IntegerField(choices=[(1, 'Giỏi'), (2, 'Khá'), (3, 'Trung Bình'), (4, 'Yếu'), (5, 'Kém'), (-1, 'Chưa đánh giá')], default=-1)),
                ('hoc_ky', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='qldh.hocky')),
                ('mahs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qldh.hocsinh')),
                ('nam_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qldh.namhoc')),
            ],
        ),
        migrations.DeleteModel(
            name='KetQuaHocTap',
        ),
    ]
