# Generated by Django 4.0.1 on 2022-04-30 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qldh', '0035_hanhkiem_delete_ketquahoctap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giaovien',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='hocsinh',
            name='profile_pic',
        ),
    ]
