# Generated by Django 4.0.1 on 2022-05-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qldh', '0036_remove_giaovien_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lophoc',
            name='meetLink',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='lophoc',
            name='requestId',
            field=models.TextField(default=''),
        ),
    ]
